config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put 'publish', 'review', 'cancel'
    end
  end

  get 'format_post', to: 'posts#format_post'
  get "/dashboard", to: "home#special_dashboard"
  root to: "home#welcome"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == "admin"
      can :manage, :all
    elsif user.role == "author"
      can :manage, Post
    else user.role == "reviewer"
      can :manage, Post
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  validates_presence_of :post
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend  FriendlyId
  include AASM

  belongs_to :user
  has_many   :images, dependent: :destroy
  validates  :title,:body, presence: true
  validates  :slug,  uniqueness: true, presence: true
  validates_associated          :images
  accepts_nested_attributes_for :images
  friendly_id :slug_candidates, use: :slugged

  after_create :remake_slug

  def slug_candidates
    [[:id, :title]]
  end

  def remake_slug
    self.update_attribute(:slug, nil)
    self.save!
  end

  aasm whiny_transitions: false do
    state :in_draft, initial: true
    state :reviewing
    state :published
    state :cancel

    event :review do
      transitions from: :in_draft, to: :reviewing
    end

    event :publish do
      transitions from: :reviewing, to: :published
    end

    event :cancel do
      transitions from: [:reviewing, :published], to: :in_draft
    end
  end
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  attr_accessor :roles

  has_many :posts

  ROLES = %w[admin author reviewer]

  serialize :roles

  def roles_symbols
    [role.to_sym].map
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_authorization_check

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :role])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "landing"
  skip_before_action :authenticate_user!
  def welcome
    @posts = Post.published.order('created_at DESC')
  end

  def special_dashboard
    if current_user.role == "admin"
      @posts = Post.all.order('created_at DESC')
    elsif current_user.role == "reviewer"
      @posts = Post.reviewing.order('created_at DESC')
    else
      @posts = current_user.posts.order('created_at DESC')
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource param_method: :post_params

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      @post.images.create(image: params[:image])
      flash[:success] = "Post created"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path, notice: "Update successful"
    else
      render :edit
    end
  end

  def index
    @posts = Post.published.order('created_at DESC')
  end

  def show; end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post destroyed"
  end

  def review
    @post.review!
    redirect_to posts_path
  end

  def publish
    @post.publish!
    redirect_to posts_path
  end

  def cancel
    @post.cancel!
    redirect_to posts_path
  end

  def format_post
    @post = Kramdown::Document.new(params[:raw_post], kramdown_options).to_html.html_safe
    respond_to do |format|
      format.json { render json: @post.to_json }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.friendly.find params[:id]
  end

  def kramdown_options
    { hard_wrap: false }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(text)
    Kramdown::Document.new(text, hard_wrap: true ).to_html.html_safe
  end
end

app/views/home/index.html.erb
<nav class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <li>
      <%= link_to "Home", root_path, method: :get %>
    </li>
    <%- if user_signed_in? %>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% end %>

    <%- unless user_signed_in? %>
      <li>
        <%= link_to "Log in", new_user_session_path, method: :get %>
      </li>
      <li>
        <%= link_to "Sign in", new_user_registration_path, method: :get %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/home/special_dashboard.html.erb
<%= link_to "Home", :root %>
<% if flash[:success] %>
  <div class="success"><%= flash[:success] %></div>
<%end%>
<% @posts.each do |post| %>
  <ul>
    <li>
      <%= link_to post.title, post %>
    </li>
    <li>
      <%- if current_user.role == "admin" %>
        <%= link_to "Revert", "/posts/#{post.id}/cancel", method: :put if post.aasm_state == "published" || post.aasm_state == "reviewing"%>
        <%= link_to "Publish", "/posts/#{post.id}/publish", method: :put if post.aasm_state == "reviewing"%>
      <%end%>
      <%- if current_user.role == "reviewer" %>
        <%= link_to "Publish", "/posts/#{post.id}/publish", method: :put %>
      <%end%>
      <%- if current_user.role == "author" %>
        <%= link_to "Review", "/posts/#{post.id}/review", method: :put if post.aasm_state == "in_draft" %>
      <%end%>
    </li>
  </ul>
<%end%>

app/views/home/welcome.html.erb
<nav class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <%- if user_signed_in? %>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
      <li>
        <%= link_to "Create post", new_post_path, method: :get %>
      </li>
    <% end %>

    <%- unless user_signed_in? %>
      <li>
        <%= link_to "Log in", new_user_session_path, method: :get %>
      </li>
      <li>
        <%= link_to "Sign in", new_user_registration_path, method: :get %>
      </li>
    <% end %>
  </ul>
</nav>

<%= render template: "/posts/index" %>

<%- if user_signed_in? %>
  <button type="button" class="btn">
    <%= link_to "Special dashboard", dashboard_path, method: :get %>
  </button>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogTrainee</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p>This page is not using the <strong>Landing Layout</strong></p>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogTrainee</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <h1>Welcome!</h1>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </br>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container-fluid">
  <div class="row-content">
    <div class="col-sm-6">
      <%= form_for @post, html: { multipart: true }  do |f| %>

        <% if @post.errors.any? %>
          <div id="error_explanation">
            <%= pluralize(@post.errors.count, "error") %>
            prohibited this article from beign saved:
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <%end%>
            </ul>
          </div>
        <%end%>

        <div class="title-field">
          <%= f.label :title %>
          <%= f.text_field :title, placeholder: "Entitle me" %>
        </div>
        <div class="body-field">
          <%= f.label :body %>
          <%= f.text_area :body, placeholder: "Place your words here" %>
        </div>
        <div class="image-field">
          <%= label_tag "image" %>
          <%= file_field_tag "image"  %>
        </div>
        <div class="actions">
          <%= f.submit "Create Post"%>
        </div>
    </div>
  <%end%>

  <div class="col-sm-6">
    <div id="output"></div>
  </div>
  </div>
</div>
<button type="button" class="btn">
  <%= link_to "Home", :root %>
</button>

app/views/posts/edit.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <ul>
    <li>
      <%= link_to post.title, post %>
    </li>
  </ul>
<%end%>

app/views/posts/new.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<%- if current_user.role == "admin" || current_user.role == "reviewer" %>
  <%= link_to "Edit", edit_post_path(@post) %>
<%- elsif @post.aasm_state == "in_draft" %>
  <%= link_to "Edit", edit_post_path(@post) %>
<%end%>
<%- if current_user.role == "admin" || current_user.role == "reviewer"%>
  <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "You sure?" } %>
<%end%>

<% if @post.images.any? %>

  <div class="hero-unit">
    <div class="hero-title">
      <%= @post.title %>
      <div class="hero-button btn-default">
        <%= link_to "Back to Home", :root %>
      </div>
    </div>

    <div class="hero-img">
      <%= image_tag @post.images.first.image_url %>
    </div>
  </div>
<%end%>

<div class="post-body">
  <%= render_markdown @post.body %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>